include $(ROOTDIR)/.config

# add extra CFLAGS
CFLAGS +=

# add .c files
CSRC:=

# add .S files
ASMSRC:=

# add sub-directories
MODULE:= ringbuf \


# include build.mk
include $(SCRIPTSDIR)/build.mk

