# add extra CFLAGS
CFLAGS +=

# add .c files
CSRC:= misc.c
CSRC += stm32f4xx_adc.c
CSRC +=	stm32f4xx_can.c
CSRC +=	stm32f4xx_crc.c
CSRC +=	stm32f4xx_cryp_aes.c
CSRC +=	stm32f4xx_cryp.c
CSRC +=	stm32f4xx_cryp_des.c
CSRC +=	stm32f4xx_cryp_tdes.c
CSRC +=	stm32f4xx_dac.c
CSRC +=	stm32f4xx_dbgmcu.c
CSRC +=	stm32f4xx_dcmi.c
CSRC +=	stm32f4xx_dma.c
CSRC +=	stm32f4xx_exti.c
CSRC +=	stm32f4xx_flash.c
CSRC +=	stm32f4xx_fsmc.c
CSRC +=	stm32f4xx_gpio.c
CSRC +=	stm32f4xx_hash.c
CSRC +=	stm32f4xx_hash_md5.c
CSRC +=	stm32f4xx_hash_sha1.c
CSRC +=	stm32f4xx_i2c.c
CSRC +=	stm32f4xx_iwdg.c
CSRC +=	stm32f4xx_pwr.c
CSRC +=	stm32f4xx_rcc.c
CSRC +=	stm32f4xx_rng.c
CSRC +=	stm32f4xx_rtc.c
CSRC +=	stm32f4xx_sdio.c 
CSRC +=	stm32f4xx_spi.c 
CSRC +=	stm32f4xx_syscfg.c
CSRC +=	stm32f4xx_tim.c
CSRC +=	stm32f4xx_usart.c
CSRC +=	stm32f4xx_wwdg.c

# add .S files
ASMSRC:= 

# add sub-directories
MODULE:= 


# include build.mk
include $(SCRIPTSDIR)/build.mk

