# add extra CFLAGS
CFLAGS +=

# add .c files
CSRC:= context.c \
       arch_init.c \
       arch_debug.c

# add .S files
ASMSRC:= context_switch.S \

# add sub-directories
MODULE:=


# include build.mk
include $(SCRIPTSDIR)/build.mk

