# add extra CFLAGS
CFLAGS += -Wno-misleading-indentation

# add .c files
CSRC:= system_stm32f4xx.c \
       stm32f4xx_it.c

# add .S files
ASMSRC:= startup_stm32f4xx.S

# add sub-directories
MODULE:=


# include build.mk
include $(SCRIPTSDIR)/build.mk

