# add extra CFLAGS
CFLAGS +=

# add .c files
CSRC:=

# add .S files
ASMSRC:=

# add sub-directories
MODULE :=
#MODULE:= mailbox
#MODULE += mutex
#MODULE += sched
#MODULE += semphore
#MODULE += signal
#MODULE += thread
#MODULE += timer
#MODULE += watchdog
#MODULE += mem
MODULE += kdebug


# include build.mk
include $(SCRIPTSDIR)/build.mk

