# add extra CFLAGS
CFLAGS +=

# add .c files
CSRC:= irq.c \
	   sched.c \
	   task.c \
	   tick.c \
	   idle.c \
	   init.c \

# add .S files
ASMSRC:=

# add sub-directories
MODULE := mm
MODULE += kdebug

# include build.mk
include $(SCRIPTSDIR)/build.mk

