# add extra CFLAGS
CFLAGS +=

# add .c files
CSRC:= mem.c \
       umm_integrity.c \
	   umm_malloc.c \
	   umm_poison.c \

# add .S files
ASMSRC:=

# add sub-directories
MODULE:= 


# include build.mk
include $(SCRIPTSDIR)/build.mk

