include $(ROOTDIR)/.config

# add extra CFLAGS
CFLAGS +=

# add .c files
CSRC:= board.c \
	   stm32f4xx_it.c \
	   system_stm32f4xx.c

# add .S files
ASMSRC:= startup_stm32f4xx.S

# add sub-directories
MODULE:=


# include build.mk
include $(SCRIPTSDIR)/build.mk

