include $(ROOTDIR)/.config

# add extra CFLAGS
CFLAGS +=

# add .c files
CSRC:= ringbuf.c

# add .S files
ASMSRC:=

# add sub-directories
MODULE:=


# include build.mk
include $(SCRIPTSDIR)/build.mk

